import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { api } from "../services/api.js";

export const ReportPage = () => {
  const { reportId } = useParams();

  const { data: report, isLoading, error } = useQuery({
    queryKey: ["report", reportId],
    queryFn: () => api.reports.get(reportId),
    enabled: Boolean(reportId)
  });

  if (isLoading) {
    return <div className="p-20 text-center">Loading report...</div>;
  }

  if (error || !report) {
    return <div className="p-20 text-center text-rose">Report not found.</div>;
  }

  const analysis = report.analysisJobId || {};
  const diagnostics = analysis.diagnostics || [];
  const recommendations = analysis.aiRecommendations || [];

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    toast.success("Link copied");
  };

  return (
    <div className="bg-white p-8 print:p-0">
      <div className="flex justify-between print:hidden mb-8">
        <button onClick={handleShare} className="px-4 py-2 border rounded">Share</button>
        <button onClick={() => window.print()} className="px-4 py-2 border rounded bg-signal text-white">Print</button>
      </div>

      <header className="mb-10">
        <h1 className="text-3xl font-bold">{report.title}</h1>
        <p className="text-zinc-500">
          Generated on: {new Date(report.generatedAt).toLocaleDateString()}
        </p>
      </header>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Performance Score</h2>
        <div className="p-6 bg-cloud rounded-lg text-center">
          <div className="text-6xl font-bold text-signal">{analysis.performanceScore ?? "N/A"}</div>
          <p className="text-xl font-medium">{analysis.scoreBand || "Unrated"}</p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Executive Summary</h2>
        <p className="text-zinc-700 leading-relaxed">
          {report.summary || "Account is performing within expected benchmarks."}
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-4">Critical Issues</h2>
        <table className="w-full border-collapse">
          <thead>
            <tr className="border-b bg-zinc-50 text-left">
              <th className="p-3">Issue</th>
              <th className="p-3">Campaign</th>
            </tr>
          </thead>
          <tbody>
            {diagnostics.filter((item) => item.severity === "critical").map((item, index) => (
              <tr key={`${item.flagType}-${index}`} className="border-b">
                <td className="p-3">{item.description}</td>
                <td className="p-3">{item.affectedEntity}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4">Top Recommendations</h2>
        <ul className="space-y-4">
          {recommendations.slice(0, 5).map((recommendation, index) => (
            <li key={`${recommendation.title}-${index}`} className="p-4 border rounded">
              <h4 className="font-semibold">{recommendation.title}</h4>
              <p className="text-sm text-zinc-600">{recommendation.description}</p>
            </li>
          ))}
        </ul>
      </section>

      <footer className="mt-20 pt-10 border-t text-center text-zinc-400 text-sm">
        Generated by AdsPulse
      </footer>
    </div>
  );
};

export default ReportPage;
